
server.port =9096
# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_achats_fournisseurs?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA and Hibernate properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update




